Repository kalviumcommunity/S85_Shivansh-Garg_Capstone_Notora, pull requests merged in 2025-06, with the labels that each got.

#23 Home Page Done
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Announcements.jsx
  frontend/src/components/Background.jsx
  frontend/src/components/CTA.jsx
  frontend/src/components/Decor.jsx
  frontend/src/components/Features.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Hero.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/Testimonials.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/components/ui/Badge.jsx
  frontend/src/components/ui/Card.jsx
  frontend/src/components/ui/button.jsx
  frontend/src/lib/utils.js
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
  frontend/tailwind.config.js
  frontend/vite.config.js
Labels: Review effort 3/5

#26 Notes page
  backend/middlewares/authMiddleware.js
  backend/passport/google.js
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/ui/input.jsx
  frontend/src/components/ui/select.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/NotesPage.jsx
  frontend/src/pages/SocialLoginButtons.jsx
Labels: Review effort 3/5

#35 Issue fixed regarding Deployment
  backend/.env.development
  backend/passport/google.js
  backend/routes/googleAuthRoutes.js
  backend/server.js
  frontend/.env.development
  frontend/src/components/Navbar.jsx
  frontend/src/components/ThemeToggle.jsx
  frontend/src/pages/AdminDashboard.jsx
  frontend/src/pages/GoogleCallback.jsx
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/NotesPage.jsx
  frontend/src/pages/PremiumPage.jsx
  frontend/src/pages/SocialLoginButtons.jsx
Labels: Review effort 1/5

#37 Issues Fixed 7.0
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/GoogleCallback.jsx
Labels: Review effort 2/5

#48 Premium users are valid now
  backend/controllers/authController.js
  backend/routes/authRoutes.js
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/NotesPage.jsx
Labels: Review effort 3/5

#56 Issue Fixed
  frontend/src/pages/PremiumPage.jsx
Labels: Review effort 2/5

#59 add modern Scroll to Top button on Notes page
  frontend/src/pages/NotesPage.jsx
Labels: Review effort 2/5

#61 Create healthRoutes.js
  backend/routes/healthRoutes.js
Labels: Review effort 1/5

#62 Errors fixed
  backend/routes/healthRoutes.js
  backend/server.js
Labels: Review effort 2/5
